version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cardgame-server"
s3_bucket = "cardgame-server-bucket"
s3_prefix = "app"
region = "ap-northeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
