AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FastAPI on Lambda

Parameters:
  MongoUri:
    Type: String
    Description: MongoDB URI
    Default: default value


Resources:
  Function: # SAM Local에서 호출하는 함수
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "FastAPILambda"  # Lambda Function Name
      Handler: app.main.handler # Lambda Handler 함수의 위치
      Runtime: python3.9
      Environment:
        Variables:
          ENV_STATE: prod
          MONGO_URI: !Ref MongoUri
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api

  Api:
    Type: AWS::Serverless::HttpApi

Outputs:
  ApiUrl:
    Description: URL of your API
    Value:
      Fn::Sub: 'https://${Api}.execute-api.${AWS::Region}.${AWS::URLSuffix}/'
